# jekyll configuration

title: "Nils Plaschke"
description: "Blog"

paginate: 10

asciidoctor:
  attributes:
    - idseparator=_
    - source-highlighter=highlightjs
    - icons=font
    - hardbreaks!

# end of configuration
